baseURL = ""
title = "Ben Thinking"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "JSON"]

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.cn]
contentDir = "content/cn"
languageName = "中文"
weight = 2
languageCode = "zh-cn"
disqusShortname = "maopanfeng"  
