baseURL = 'https://maopanfeng.com/'
languageCode = 'zh-cn'
title = 'Ben Thinking'
theme = 'paper'

[params]
    name = "Ben"
    description = "Complexity Investing"
    # 找回搜索的关键开关
    search = true 

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Wiki"
    url = "/wiki"
    weight = 20
  [[menu.main]]
    name = "搜索"
    url = "/search"
    weight = 30
  [[menu.main]]
    name = "关于"
    url = "/about"
    weight = 40

# 必须生成 JSON，否则你的搜索功能无法运行
[outputs]
  home = ["HTML", "RSS", "JSON"]