baseURL = 'https://maopanfeng.com/'
languageCode = 'zh-cn'
title = 'Complexity Investing'
theme = 'paper'

[params]
description = "Exploring Value in Non-Linear Systems"

[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "About"
url = "/about/"
weight = 20
